### ISSUE TITLE
Need to remove pagination when using Jetpack infinite scroll

### ISSUE THREAD

**Issue by BenSibley** [BenSibley/Founder#16]
Check Apex.

**Comment by alokroutray** [comment]
Same problem here. Please help !!!

**Comment by BenSibley** [comment]
This issue has been fixed in a previous version of Founder. If it's still an issue, try updating to the latest version of Founder, or deactivate your plugins to check for a conflict with a plugin on the site.

**Comment by alokroutray** [comment]
Hi Ben Sibley,

Thank you for reply. I got it. I changed it in the module page.

_Regards,_
_Alok Kumar Routray_

http://www.behance.net/alokkumarroutray
_https://in.linkedin.com/in/routrayalok
https://in.linkedin.com/in/routrayalok_
_http://orangescorpio.com/ http://orangescorpio.com/_

Skype  : _alokkumarroutray_
Mobile  : _+91-720-5255-859_
