### ISSUE TITLE
Missing i18n

### ISSUE THREAD

**Issue by spotman** [BenSibley/Founder#19]
Hi there!

I'm using your Founder theme (it's awesome!) and want to buy Pro version but I've found issues with i18n for ru_RU: some strings aren't localized. For example, `Published %1$s by %2$s` is shown in English, but `ru_RU.po` file contains this string. I've discovered that setting `context` argument of `esc_html_x` function to `null` fixes this issue. I'm not a WP localization expert so I can not detect the source of the problem (`ru_RU.po` file or incorrect usage of `esc_html_x` function).

May you help me with this issue?
Thanks!

**Comment by BenSibley** [comment]
Thanks for pointing out this error! I will address it in the next update this week and find a solution.

**Comment by spotman** [comment]
Ben, had you fixed this issue and may I update the theme to check it?

**Comment by BenSibley** [comment]
Thanks for your patience with this issue. 

I could not find a pattern for why certain uses of _x() functions with certain languages fail, so for now, I've replaced them with alternate i18n functions that are working properly. 

Version 1.36 will be available for download in your dashboard in just a few minutes.

**Comment by spotman** [comment]
Ben, I've updated the theme and most of i18n issues are gone, thanks for that! But I still see original English words in some cases:

- `Comments` in comments form header here https://github.com/BenSibley/Founder/blob/18cb39f3e0918ecd43314e6854d979b3a2bcbcc1/comments.php#L23 in case of no comments
- `Search...` as a placeholder of search field in header (looks like you've missed `...` in `ru_RU.po` file)
- `Previous` and `Next` words in pagination (I had not found translations in `ru_RU.po` but correct translations are `Предыдущая` and `Следующая`)

**Comment by BenSibley** [comment]
Thanks for pointing out these remaining issues. I'm publishing the new update now and it will be available for download shortly

**Comment by spotman** [comment]
Thanks, Ben! I think everything would be OK for now.
